radio:
  1:
    model: Anytone 878UV Plus
    configuration:
      firmware: 3.06
      max_channels_per_scanlist: 50
      max_channels: 4000
      max_zones: 250
      max_channel_per_zone: 250
      max_channel_name_characters: 16
      max_zone_name_characters: 16
      max_scanlist_name_characters: 16
      max_talkgroups: 10000
      min_frequency: 136
      max_frequency: 480
      color_code_min: 0
      color_code_max: 15
      ctcss_min: 0
      ctcss_max: 300
      bandwidth:
        wide: 25K
        narrow: 12.5K
      list_separator: "|"
      values:
        channel_type:
          analog: A-Analog
          digital: D-Digital
        time_slot_none: '-'
        tx_permit:
          channel_free: ChannelFree
          same_color_code: Same Color Code
          different_color_code: Different Color Code
          always: Always
        call_type:
          group_call: Group Call
          private_call: Private Call
        squelch_mode_ctcss_dcs: CTCSS/DCS
        dmr_mode:
          simplex: 0
          repeater: 1
        power_levels: [Low, Mid, High, Turbo]
        bandwidths: [12.5K, 25K]
        timeslots: ['1', '2', '-']
        on_off: ['On', 'Off']
      channel_defaults:
        No.: REQUIRED
        Channel Name: REQUIRED
        Receive Frequency: REQUIRED
        Transmit Frequency: REQUIRED
        Channel Type: REQUIRED
        Transmit Power: High
        Band Width: 12.5K
        CTCSS/DCS Decode: 'Off'
        CTCSS/DCS Encode: 'Off'
        Contact: 
        Contact Call Type: Group Call
        Contact TG/DMR ID: 
        Radio ID: DMR ID
        Busy Lock/TX Permit: Same Color Code
        Squelch Mode: Carrier
        Optional Signal: 'Off'
        DTMF ID: 1
        2Tone ID: 1
        5Tone ID: 1
        PTT ID: 'Off'
        RX Color Code: 0
        Slot: 1
        Scan List: REQUIRED
        Receive Group List: 'None'
        PTT Prohibit: 'Off'
        Reverse: 'Off'
        Simplex TDMA: 'Off'
        Slot Suit: 'Off'
        AES Digital Encryption: Normal Encryption
        Digital Encryption: 'Off'
        Call Confirmation: 'Off'
        Talk Around(Simplex): 'Off'
        Work Alone: 'Off'
        Custom CTCSS: 0
        2TONE Decode: 1
        Ranging: 'Off'
        Through Mode: 'Off'
        APRS RX: 'Off'
        Analog APRS PTT Mode: 'Off'
        Digital APRS PTT Mode: 'Off'
        APRS Report Type: 'Analog'
        Digital APRS Report Channel: 1
        Correct Frequency[Hz]: 0
        SMS Confirmation: 'Off'
        Exclude channel from roaming: 0
        DMR MODE: 0
        DataACK Disable: 0
        R5toneBot: 0
        R5ToneEot: 0
        Auto Scan: 0
        Ana Aprs Mute: 0
        Send Talker Alias: 0
        AnaAprsTxPath: 0
        ARC4: 0
        ex_emg_kind: 0
        TxCC: 0
  2:
    model: Anytone 878UV Plus
    configuration:
      firmware: 3.05
      max_channels_per_scanlist: 50
      max_channels: 4000
      max_zones: 250
      max_channel_per_zone: 250
      max_channel_name_characters: 16
      max_zone_name_characters: 16
      max_scanlist_name_characters: 16
      max_talkgroups: 10000
      min_frequency: 136
      max_frequency: 480
      color_code_min: 0
      color_code_max: 15
      ctcss_min: 0
      ctcss_max: 300
      bandwidth:
        wide: 25K
        narrow: 12.5K
      list_separator: "|"
      values:
        channel_type:
          analog: A-Analog
          digital: D-Digital
        time_slot_none: '-'
        tx_permit:
          channel_free: ChannelFree
          same_color_code: Same Color Code
          different_color_code: Different Color Code
          always: Always
        call_type:
          group_call: Group Call
          private_call: Private Call
        squelch_mode_ctcss_dcs: CTCSS/DCS
        dmr_mode:
          simplex: 0
          repeater: 1
        power_levels: [Low, Mid, High, Turbo]
        bandwidths: [12.5K, 25K]
        timeslots: ['1', '2', '-']
        on_off: ['On', 'Off']
      channel_defaults:
        No.: REQUIRED
        Channel Name: REQUIRED
        Receive Frequency: REQUIRED
        Transmit Frequency: REQUIRED
        Channel Type: REQUIRED
        Transmit Power: High
        Band Width: 12.5K
        CTCSS/DCS Decode: 'Off'
        CTCSS/DCS Encode: 'Off'
        Contact: 
        Contact Call Type: Group Call
        Contact TG/DMR ID: 
        Radio ID: DMR ID
        Busy Lock/TX Permit: Same Color Code
        Squelch Mode: Carrier
        Optional Signal: 'Off'
        DTMF ID: 1
        2Tone ID: 1
        5Tone ID: 1
        PTT ID: 'Off'
        Color Code: 0
        Slot: 1
        Scan List: REQUIRED
        Receive Group List: 'None'
        PTT Prohibit: 'Off'
        Reverse: 'Off'
        Simplex TDMA: 'Off'
        Slot Suit: 'Off'
        AES Digital Encryption: Normal Encryption
        Digital Encryption: 'Off'
        Call Confirmation: 'Off'
        Talk Around(Simplex): 'Off'
        Work Alone: 'Off'
        Custom CTCSS: 0
        2TONE Decode: 1
        Ranging: 'Off'
        Through Mode: 'Off'
        APRS RX: 'Off'
        Analog APRS PTT Mode: 'Off'
        Digital APRS PTT Mode: 'Off'
        APRS Report Type: 'Analog'
        Digital APRS Report Channel: 1
        Correct Frequency[Hz]: 0
        SMS Confirmation: 'Off'
        Exclude channel from roaming: 0
        DMR MODE: 0
        DataACK Disable: 0
        R5toneBot: 0
        R5ToneEot: 0
        Auto Scan: 0
        Ana Aprs Mute: 0